### PR TITLE
Fix auth tests

### PR DESCRIPTION
**Pull request by rafaelcaricio**
Fix tests failing on master. Reflects that authenticated clients requests to unknown endpoints should return `404`.

Other changes:
- Upgrade Flask to 0.11.1
- Better way to add default error handlers, new in Flask 0.11.1

### CODE REVIEW

**Comment by jmcs** [comment]
Can you change the travis.yml to avoid the flake8 pickling error?

**Comment by rafaelcaricio** [comment]
Yes, I will try to downgrade the flake8 version and see if the problem persists. Related bug: https://gitlab.com/pycqa/flake8/issues/164

**Comment by rafaelcaricio** [comment]
@jmcs passing. 👍

**Comment by jmcs** [comment]
:+1:

**Pull request merged**
