### PR TITLE
Use fixed version of Connexion

### PR DESCRIPTION
**Pull request by rafaelcaricio**
Use fixed version connexion==1.1.5 while code is not upgraded.

### CODE REVIEW

**Comment by jmcs** [comment]
:+1:

**Comment by rafaelcaricio** [comment]
👍

**Comment by jmcs** [comment]
:+1:

**Comment by hjacobs** [comment]
@rafaelcaricio what's the problem with a newer version of Connexion? I thought everything is now backwards compatible?

**Comment by rafaelcaricio** [comment]
@hjacobs because in this project we are doing this https://github.com/zalando/lizzy/blob/master/lizzy/serialization.py#L6

I will clean this up tomorrow and let Lizzy use the latest Connexion version.

**Pull request merged**
