### PR TITLE
Support the same template parameters as senza

### LINKED ISSUE #71: Provide the same arguments as Senza to the template
Lizzy should provide the same parameters to pystach renderer that senza does (see [senza.cli.evaluate](https://github.com/zalando-stups/senza/blob/2348a1dc0a860d8ce3f134cd5d1289a956a47860/senza/cli.py#L210) and [senza.components,evaluate_template](https://github.com/zalando-stups/senza/blob/4e3496b419e351798e6933ca6c60525c71fec1d9/senza/components/__init__.py#L21))

### PR DESCRIPTION
**Pull request by jmcs**
Fixes #71.

### CODE REVIEW

**Comment by jmcs** [comment]
@hjacobs @prayerslayer Your input would also be useful on this Pull Request.

**Comment by rafaelcaricio** [comment]
@jmcs Is this PR the first part of Lizzy that will make it dependent of internal behaviour of senza package?

**Comment by jmcs** [comment]
Yes, it's the first time we import from senza, but we were already dependent on it's behavior. That's the reason I asked for feedback from @hjacobs and @prayerslayer.

**Comment by jmcs** [comment]
Not needed anymore do to #77.

**Pull request closed without merging**
