### PR TITLE
Add health check endpoint

### LINKED ISSUE #125: Provide a health endpoint
Please provide a **health** endpoint that allows any tool to ensure that the instance is healthy.

Usually at `/health`

### PR DESCRIPTION
**Pull request by rafaelcaricio**
Fixes #125

### CODE REVIEW

**Comment by jmcs** [comment]
:+1:

**Comment by jmcs** [comment]
@rafaelcaricio can you solve the conflicts?

**Comment by rafaelcaricio** [comment]
@jmcs done.

**Comment by jmcs** [comment]
:+1:

**Pull request merged**
