### PR TITLE
Wait for long running commands to finish

### PR DESCRIPTION
**Pull request by rafaelcaricio**
Some Senza commands like `senza delete <stackid>` takes long to run, let uWSGI wait a little longer for these requests.

### CODE REVIEW

**Comment by kabdelrahman** [comment]
👍

**Comment by kabdelrahman** [comment]
Thanks for fixing this annoying issue :-)

**Comment by jmcs** [comment]
:+1:

**Comment by rafaelcaricio** [comment]
@jmcs @kabdelrahman need thumbs up again... :)

**Comment by jmcs** [comment]
:+1:

**Pull request merged**
