### PR TITLE
fix 400 errors on lizzy traffic

### PR DESCRIPTION
**Pull request by mfelsche**
We experienced some 400 errors when issuing lizzy traffic <STACK> <STACK_VERSION> 0 on the last existing stack:

```
11:51:00 + lizzy version
11:51:00 Lizzy Client 1.8
11:51:00 + lizzy traffic <> 0
11:51:01 Fetching authentication token.. . OK

11:51:01 Requesting traffic change..Data Json:
11:51:05  EXCEPTION OCCURRED: 400 Client Error: BAD REQUEST for url: https://lizzy-nuggad.nuggad.zalan.do/api/stacks/zk-kafka-3
11:51:05 {
11:51:05     "new_traffic": 0
11:51:05 }
11:51:05 Traceback (most recent call last):
11:51:05   File "/usr/local/bin/lizzy", line 11, in <module>
11:51:05     sys.exit(main())
11:51:05   File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 716, in __call__
11:51:05     return self.main(*args, **kwargs)
11:51:05   File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 696, in main
11:51:05     rv = self.invoke(ctx)
11:51:05   File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1060, in invoke
11:51:05     return _process_result(sub_ctx.command.invoke(sub_ctx))
11:51:05   File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 889, in invoke
11:51:05     return ctx.invoke(self.callback, **ctx.params)
11:51:05   File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 534, in invoke
11:51:05     return callback(*args, **kwargs)
11:51:05   File "/usr/local/lib/python3.4/dist-packages/lizzy_client/cli.py", line 207, in traffic
11:51:05     lizzy.traffic(stack_id, percentage)
11:51:05   File "/usr/local/lib/python3.4/dist-packages/lizzy_client/lizzy.py", line 126, in traffic
11:51:05     request.raise_for_status()
11:51:05   File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 840, in raise_for_status
11:51:05     raise HTTPError(http_error_msg, response=self)
```

It seems lizzy expects JSON output but does not accept empty output. In the case described above, senza outputs nothing: https://github.com/zalando-stups/senza/blob/master/senza/traffic.py#L343 

This PR contains a fix for that edge case.

### CODE REVIEW

**Comment by jmcs** [comment]
Thanks for the PR. Can you resolve the merge conflicts?

**Comment by rafaelcaricio** [comment]
LGTM.

**Comment by rafaelcaricio** [comment]
👍

**Comment by mfelsche** [comment]
rebased on master

**Comment by rafaelcaricio** [comment]
👍

**Comment by jmcs** [comment]
:+1:

**Comment by rafaelcaricio** [comment]
:+1:

**Pull request merged**
